### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by raphaabrasil** [raphaabrasil/flashcards#1]
At this point, we still have a couple of things to do. Here they are:
- [x] Notify users if they dont open the app in the day

### Deck View 
- [x] Shows the number of cards on deck

### Quiz View
- [x] Shows the remaining cards to complete the quiz

**Comment by raphaabrasil** [comment]
All solved :)
